CREATE TABLE IF NOT EXISTS shuguang.shuguang_dwd_game_PlayerBattle_d
(
    battle_id    bigint    comment '对局id',
    battle_tid    int    comment '对局配置id',
    role_id    bigint    comment '玩家的UID',
    camp_id    int    comment '阵营ID',
    hero_tid    int    comment '英雄ID',
    elo    int    comment 'elo分当前',
    team_elo    int    comment '队伍elo分',
    battle_sum    int    comment '对局总数 现个人界面处对局场次（当前完成的对局数，开始匹配，对局，对局结束后，都为前一场；当开始下一场匹配时+1）',
    leader_id    bigint    comment '队长的UID',
    camp_tids    string    comment '成局人数类型 返回双方队伍组成配置id',
    equipments    string    comment '装备',
    runes    string    comment '铭文',
    masteries    string    comment '铭文专精',
    skill_id    int    comment '技能ID',
    kill    int    comment '杀人数',
    death    int    comment '死亡数',
    assist    int    comment '辅助数',
    level    int    comment '等级',
    gold    int    comment '金币',
    score    float    comment '评分',
    damage_score    float    comment '伤害评分',
    survival_score    float    comment '生存评分',
    economy_score    float    comment '经济评分',
    team_score    float    comment '团队评分',
    kda_score    float    comment 'KDA评分',
    carry_score    float    comment '推进评分',
    tower_kill    int    comment '击杀塔数目',
    creep_kill    int    comment '击杀小兵数目',
    monster_kill    int    comment '击杀野怪数目',
    damage    int    comment '总伤害',
    phy_dmg    int    comment '总物理伤害',
    mag_dmg    int    comment '总魔法伤害',
    true_dmg    int    comment '总真实伤害',
    dmg2hero    int    comment '对英雄的总伤害',
    dmg2tower    int    comment '对防御塔的总伤害',
    phydmg2hero    int    comment '对英雄的总物理伤害',
    magdmg2hero    int    comment '对英雄的总魔法伤害',
    truedmg2hero    int    comment '对英雄的总真实伤害',
    healing2hero    int    comment '对英雄造成总治疗',
    dmg_received    int    comment '承受总伤害',
    phydmg_received    int    comment '承受总物理伤害',
    magdmg_received    int    comment '承受总魔法伤害',
    truedmg_received    int    comment '承受总真实伤害',
    dmg_receivedfromhero    int    comment '承受英雄总伤害',
    phydmg_receivedfromhero    int    comment '承受英雄总物理伤害',
    magdmg_receivedfromhero    int    comment '承受英雄总魔法伤害',
    truedmg_receivedfromhero    int    comment '承受英雄总真实伤害',
    dmg2creep    int    comment '对小兵总伤害',
    dmg2monster    int    comment '对野怪总伤害',
    ip    string    comment 'ip地址',
    rank    int    comment '段位（旧）',
    rank_tid    int    comment '段位',
    rank_star    int    comment '星级',
    victory    int    comment '胜利为1 失败为0',
    afk_times    int    comment '挂机次数',
    is_afk_punish    int    comment '是否挂机惩罚',
    triblekill    int    comment '三杀次数',
    quadrakill    int    comment '四杀次数',
    pentakill    int    comment '五杀次数',
    legendary    int    comment '超神次数'
)
    COMMENT '玩家对局信息'
    partitioned by (year string, month string, day string)
    stored as TEXTFILE ;


select
    pb.battleid,
    pb.battletid,
    pb.role_id,
    pb.factionid,
    pb.herotid,
    me.elo,
    me.team_elo,
    me.battle_sum,
    me.leader_id,
    me.camp_tids,
    pb.equipments,
    pb.runes,
    pb.masteries,
    pb.skillid,
    pb.kill,
    pb.death,
    pb.assist,
    pb.level,
    pb.gold,
    pb.score,
    pb.damagescore,
    pb.survivalscore,
    pb.economyscore,
    pb.teamscore,
    pb.teamscore,
    pb.kdascore,
    pb.carryscore,
    pb.towerkill,
    pb.soldierkill,
    pb.creepkill,
    pb.damage,
    pb.phydmg,
    pb.magdmg,
    pb.truedmg,
    pb.dmgtohero,
    pb.dmgtotower,
    pb.phydmgtohero,
    pb.magdmgtohero,
    pb.truedmgtohero,
    pb.healingtohero,
    pb.dmgreceived,
    pb.phydmgreceived,
    pb.magdmgreceived,
    pb.truedmgreceived,
    pb.dmgreceivedfromhero,
    pb.phydmgreceivedfromhero,
    pb.magdmgreceivedfromhero,
    pb.truedmgreceivedfromhero,
    pb.dmgtosoldier,
    pb.dmgtocreep,
    pb.ip,
    pb.rank,
    pb.rank_tid,
    pb.rank_star,
    pb.victory,
    pb.disconnect_times,
    pb.is_disconnect,
    pb.triblekill,
    pb.quadrakill,
    pb.pentakill,
    pb.legendary
from
    shuguang_ods_game_playerbattle_d pb inner join shuguang_ods_game_matchingensure_d me on pb.battleid = me.matching_id;