insert overwrite table shuguang.shuguang_dwd_game_t_hero_state_d_delta PARTITION(game_server_version='${game_server_version}',game_big_version_short='${game_big_version_short}',game_key_version='${game_key_version}',year='${YEAR}',month='${MONTH}',day='${DAY}')
select
-- 主键
oghs.battleid,
oghs.complete,
-- 维度
dgbt.id,
oghs.id,
oghs.account,
oghs.campid,
oghs.locationx,
oghs.locationy,
dgma.id,
oghs.curskillid,
oghs.exstate,
oghs.equiptids,
-- oghs.equipidrecommend,
oghs.heroid,
oghs.raceid,
oghs.playerlevel,
ogpb.ai_base,
ogpb.ai_type,
ogpb.deepainum,
-- 度量
oghs.directionx,
oghs.directiony,
-- getAngle(oghs.directionx, oghs.directiony),
1,
oghs.hp,
oghs.hpmax,
if (oghs.hpmax==0,0,cast(oghs.hp/oghs.hpmax*100 as decimal(10,0))),
dghps.hp_section,
oghs.energy,
oghs.energymax,
if (oghs.energymax==0,0,cast(oghs.energy/oghs.energymax*100 as decimal(10,0))),
oghs.mana,
oghs.manamax,
if (oghs.manamax==0,0,cast(oghs.mana/oghs.manamax*100 as decimal(10,0))),
dgmns.mana_section,
oghs.anger,
oghs.angermax,
if (oghs.angermax==0,0,cast(oghs.anger/oghs.angermax*100 as decimal(10,0))),
oghs.level_col,
oghs.exp,
oghs.curgold,
oghs.gold,
oghs.phyatk,
oghs.phydef,
oghs.mgcatk,
oghs.mgcdef,
oghs.toughness,
oghs.cdr,
oghs.respawn,
oghs.isvisiable,
oghs.movespeed,
oghs.kill,
oghs.dead,
oghs.assist,
oghs.hprecover,
oghs.energyrecover,
oghs.atkspeed,
oghs.crt,
oghs.crttimes,
oghs.phythrough,
oghs.magthrough,
oghs.phythroughpercent,
oghs.magthroughpercent,
oghs.spellsorb,
oghs.atksorb,
oghs.shield,
oghs.shieldphy,
oghs.shieldmgc,
oghs.shieldall,
oghs.shieldphymax,
oghs.shieldmgcmax,
oghs.shieldallmax,
oghs.headiconlockontargetiid,
oghs.chasetargetiid,
oghs.ischasemove,
oghs.isautoattacking,
oghs.lockontargetiid,
oghs.isdead,
oghs.tp_begintime,
oghs.tp_endtime,
oghs.springPortalSuccess,
-- 无事实度量，有数据就说明在此位置出现，常量1
if (oghs.isdead, 0, 1),
oghs.delcurskillid,
oghs.delexstate,
-- structTrans(oghs.abilitystate[], "id", "level_col", "usable", "cd", "cdmax", "atkrange", "hpcost","mpcost","xpcost","segment","progress","isOutofMana"),
oghs.bserverai,
oghs.elo,
oghs.score,
oghs.difficulty,
oghs.playerType,
oghs.delabilitystate
from (select * from shuguang.shuguang_ods_game_hero_state_d_delta where game_server_version='${game_server_version}'and game_big_version_short='${game_big_version_short}'and game_key_version='${game_key_version}' and year='${YEAR}' and month='${MONTH}' and day='${DAY}') oghs
         inner join (select battleid,ai_type,ai_base,deepainum,herotid from shuguang.shuguang_ods_game_PlayerBattle_d_delta where year='${YEAR}' and month='${MONTH}' and day='${DAY}') ogpb on (oghs.battleid = ogpb.battleid and oghs.heroid = ogpb.herotid)
         inner join shuguang.shuguang_dim_game_battle_time dgbt on (oghs.frameno = dgbt.frame_no and dgbt.version = '${dim_version}')
--          inner join shuguang.shuguang_dim_game_map_area dgma on (1 = dgma.area_id and dgma.version = '${version}')
         inner join shuguang.shuguang_dim_game_map_area dgma on (floor((oghs.locationx/10000-40)/12) = dgma.x_section and floor((oghs.locationy/10000-40)/12) = dgma.y_section and dgma.version = '${dim_version}')
         inner join shuguang.shuguang_dim_game_hp_section dghps on (if (oghs.hpmax==0,0,cast(oghs.hp/oghs.hpmax*100 as decimal(10,0))) = dghps.hp_percent and dghps.version = '${dim_version}')
         inner join shuguang.shuguang_dim_game_mana_section dgmns on (if (oghs.manamax==0,0,cast(oghs.mana/oghs.manamax*100 as decimal(10,0))) = dgmns.mana_percent and dgmns.version = '${dim_version}')
